# Generated by Django 3.2 on 2021-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandUser',
            fields=[
                ('system_name', models.TextField(primary_key=True, serialize=False)),
                ('displayed_name', models.TextField()),
                ('password', models.TextField()),
                ('position', models.TextField(null=True)),
                ('permission', models.TextField(choices=[('Assistant', 'Assistant'), ('Manager', 'Manager'), ('Shop owner', 'Shop owner')], default='Assistant')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
